### ISSUE TITLE
package not found ros2_robotiqgripper

### ISSUE THREAD

**Issue by T-Lemmel** [IFRA-Cranfield/ros2_SimRealRobotControl#12]
_using Ubuntu 22.04 and ros2 humble_

Hello, i get this when trying to colcon build : 

```
Starting >>> abb_libegm
Starting >>> abb_librws
Starting >>> abb_irb1200_support
Starting >>> abb_rapid_msgs
Starting >>> abb_robot_msgs
Starting >>> linkattacher_msgs
Starting >>> serial
Starting >>> abb_egm_msgs
Starting >>> abb_resources
Starting >>> gazebo_ros2_control
Starting >>> ros2srrc_data
Starting >>> abb_irb4600_support
Starting >>> abb_ros2
Starting >>> robotiq_controllers
Starting >>> robotiq_description
Starting >>> ros2srrc_dobot_gazebo
Starting >>> ros2srrc_dobot_moveit2
Starting >>> ros2srrc_irb120_bringup
Starting >>> ros2srrc_irb120_gazebo
Starting >>> ros2srrc_irb120_moveit2
Finished <<< abb_irb1200_support [0.43s]                                                                                                                    
Finished <<< abb_librws [0.45s]
Finished <<< ros2srrc_dobot_gazebo [0.41s]
Finished <<< abb_ros2 [0.43s]
Starting >>> abb_irb1200_5_90_moveit_config
Starting >>> ros2srrc_ur10e_bringup
Starting >>> ros2srrc_ur10e_gazebo
Starting >>> ros2srrc_ur10e_moveit2
Finished <<< abb_irb4600_support [0.48s]                                                                                                 
Finished <<< robotiq_description [0.47s]
Starting >>> ros2srrc_ur3_bringup
Finished <<< ros2srrc_dobot_moveit2 [0.47s]
Finished <<< ros2srrc_irb120_gazebo [0.47s]
Finished <<< abb_resources [0.51s]
Finished <<< ros2srrc_irb120_bringup [0.48s]
Finished <<< robotiq_controllers [0.50s]
Starting >>> ros2srrc_ur3_gazebo
Starting >>> ros2srrc_ur3_moveit2
Finished <<< ros2srrc_irb120_moveit2 [0.49s]
Finished <<< gazebo_ros2_control [0.55s]
Starting >>> gazebo_ros2_control_demos
Finished <<< abb_libegm [0.61s]                                                                                                           
Starting >>> abb_egm_rws_managers
Finished <<< ros2srrc_ur10e_moveit2 [0.24s]                                                                                                      
Finished <<< ros2srrc_ur10e_bringup [0.26s]
Finished <<< abb_irb1200_5_90_moveit_config [0.28s]
Finished <<< ros2srrc_ur10e_gazebo [0.28s]
Finished <<< ros2srrc_ur3_bringup [0.25s]
Starting >>> abb_bringup
Finished <<< ros2srrc_ur3_gazebo [0.25s]
Finished <<< ros2srrc_ur3_moveit2 [0.26s]                                                                                                        
Finished <<< linkattacher_msgs [0.87s]
Starting >>> ros2_linkattacher
Finished <<< gazebo_ros2_control_demos [0.33s]                                                                                                                
Finished <<< abb_egm_msgs [0.89s]
Finished <<< abb_egm_rws_managers [0.32s]
Starting >>> abb_hardware_interface
Finished <<< abb_bringup [0.20s]
Finished <<< ros2_linkattacher [0.20s]                                                                                                                             
Finished <<< abb_hardware_interface [0.20s]                                                                                                                     
Finished <<< abb_rapid_msgs [1.13s]
Finished <<< ros2srrc_data [1.11s]
Starting >>> abb_rapid_sm_addin_msgs
Finished <<< serial [1.36s]                                                                                                               
Starting >>> robotiq_driver
Finished <<< abb_robot_msgs [1.50s]                                                                                                          
Starting >>> ros2srrc_execution
Finished <<< abb_rapid_sm_addin_msgs [0.76s]                                                                                                   
Starting >>> abb_rws_client
Finished <<< abb_rws_client [0.17s]                                                                                                   
--- stderr: ros2srrc_execution                                                                         
CMake Error at CMakeLists.txt:47 (find_package):
  By not providing "Findros2_robotiqgripper.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "ros2_robotiqgripper", but CMake did not find one.

  Could not find a package configuration file provided by
  "ros2_robotiqgripper" with any of the following names:

    ros2_robotiqgripperConfig.cmake
    ros2_robotiqgripper-config.cmake

  Add the installation prefix of "ros2_robotiqgripper" to CMAKE_PREFIX_PATH
  or set "ros2_robotiqgripper_DIR" to a directory containing one of the above
  files.  If "ros2_robotiqgripper" provides a separate development package or
  SDK, be sure it has been installed.


---
Failed   <<< ros2srrc_execution [2.28s, exited with code 1]
Aborted  <<< robotiq_driver [6.19s]                                  

Summary: 34 packages finished [7.72s]
  1 package failed: ros2srrc_execution
  1 package aborted: robotiq_driver
  1 package had stderr output: ros2srrc_execution
  1 package not processed
```
I haven't found this **ros2_robotiqgripper** online so i'm not sure what is the problem. 

Can you help me please ? 
Thanks a lot in advance,
Tom

**Comment by seungwon-jang** [comment]
I have same issue! Did you find a solution?

**Comment by CrisicGgbond** [comment]
I also have same issue!

**Comment by CrisicGgbond** [comment]
> I also have same issue!

CMake Error at CMakeLists.txt:47 (find_package):
  By not providing "Findros2_robotiqgripper.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "ros2_robotiqgripper", but CMake did not find one.

  Could not find a package configuration file provided by
  "ros2_robotiqgripper" with any of the following names:

    ros2_robotiqgripperConfig.cmake
    ros2_robotiqgripper-config.cmake

  Add the installation prefix of "ros2_robotiqgripper" to CMAKE_PREFIX_PATH
  or set "ros2_robotiqgripper_DIR" to a directory containing one of the above
  files.  If "ros2_robotiqgripper" provides a separate development package or
  SDK, be sure it has been installed.

**Comment by T-Lemmel** [comment]
Yes @CrisicGgbond you are right this is the problem but the package `ros2_robotiqgripper` would need to be installed before adding anything to CMAKE_PREFIX_PATH, and i couldn't find a package named like that anywhere. 

The closest one i found is a repository called `ros2_robotiq_gripper` but none of the package in it have the `ros2_robotiqgripper`  name. My guess is that those in charge of this package changed the structure of the project and ros2_SimRealRobotControl hasn't been adapted yet but we would need someone to confirm that. 

PS : `ros2_robotiqgripper repository :`  https://github.com/PickNikRobotics/ros2_robotiq_gripper

**Comment by NilsHeidemann** [comment]
While we are waiting for the fix you can do the following:
You can build the package without using the ros2_robotiqgripper package.
Just delete everything with "robotiq" inside the package ros2srrc_execution. I deleted the following lines:
In CMakeLists.txt:    Line 47:            find_package(ros2_robotiqgripper REQUIRED)
In CMakeLists.txt:    Line 131:          ros2_robotiqgripper
In package.xml:       Line 27:            depend ros2_robotiqgripper /depend
In sequence.cpp:     Line 47:            #include <ros2_robotiqgripper/srv/robotiq_gripper.hpp>
In sequence.cpp:     Line 95:            std::shared_ptr<rclcpp::Node> URRobotiqGripperNode;
In sequence.cpp:     Line 296-327:   Section with UR Robotiq GRIPPER: Open/Close
In sequence.cpp:     Line 682-699:   Section with UR Robot - Robotiq Gripper -> Gripper OPEN/CLOSE
In sequence.cpp:     Line 748-752:   Section with Declare UR Robotiq-HandE Gripper node

**Comment by MikelBueno** [comment]
Hi all, 

I'm sorry about this. 

I have developed a ROS 2 package that supports the control of the Robotiq Hand-E and 2f-85 grippers (when connected to UR Robots) through ROS 2, and some of the classes and functions in ros2srrc_execution depend on that package.

The problem was caused because the repository in GitHub was not made public. The problem is gone now, I have released it :)

Thanks for your feedback!
Regards,
Mikel, IFRA-Cranfield

**Comment by Huangruopeng** [comment]
We are still facing this issue with the Robotiq Gripper. This error shows up: 
`CMake Error at CMakeLists.txt:51 (find_package):
  By not providing "Findros2_robotiqgripper.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "ros2_robotiqgripper", but CMake did not find one.

  Could not find a package configuration file provided by
  "ros2_robotiqgripper" with any of the following names:

    ros2_robotiqgripperConfig.cmake
    ros2_robotiqgripper-config.cmake

  Add the installation prefix of "ros2_robotiqgripper" to CMAKE_PREFIX_PATH
  or set "ros2_robotiqgripper_DIR" to a directory containing one of the above
  files.  If "ros2_robotiqgripper" provides a separate development package or
  SDK, be sure it has been installed.`

**Comment by NilsHeidemann** [comment]
Did you install the robotiqgripper package on your workspace?
https://github.com/IFRA-Cranfield/ros2_RobotiqGripper

**Comment by Huangruopeng** [comment]
I have this issue where it cannot find the header file called move_group_interface_improved.h .

The path is set to moveit package but from what I understand, it looks like it is in the include directory on your package.

Is it an error in the code side? or am I missing something?

In file included from /home/lm-2023/AAA-Ruopeng-test/abb_ws/src/ros2_SimRealRobotControl/ros2srrc_execution/src/moveg.cpp:31:
/home/lm-2023/AAA-Ruopeng-test/abb_ws/src/ros2_SimRealRobotControl/ros2srrc_execution/include/ros2srrc_execution/moveg.h:43:10: fatal error: moveit/move_group_interface/move_group_interface_improved.h: No such file or directory
   43 | #include <moveit/move_group_interface/move_group_interface_improved.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



Thank you!
