### ISSUE TITLE
Waiting for /Move ROS2 ActionServer to be available...

### ISSUE THREAD

**Issue by greyflon** [IFRA-Cranfield/ros2_SimRealRobotControl#27]
Hello, I am a student, new to ros2, trying launching this project. I ran into a problem.
I was trying to launch execution of demo program with the command:
`ros2 run ros2srrc_execution ExecuteProgram.py package:="ros2srrc_execution" program:="irb120_demo"`
and got a response
`[CLIENT - robot.py]: Waiting for /Move ROS2 ActionServer to be available...`

But i cant find anywhere how to launch an action server. I tried launching a simulation in another terminal
`ros2 launch ros2srrc_launch moveit2.launch.py package:=ros2srrc_irb120 config:=irb120_1`
and it works, but dont launch action server either.

What should i do to run a program?

**Comment by SeanM-IRL** [comment]
facing the same issue, it looks like there was changes from sequence.py to execute_program.py, unfortunately they did not release this repo in releases so you cannot go back to see what exactly was contained in sequence, there looks to be no action server running, , hope they resolve it soon, I am very interested in their research.

**Comment by MikelBueno** [comment]
Hi @SeanM-IRL and @greyflon,

Your issue is related to the /Move ROS 2 Action Server's node, not ExecuteProgram.py. The script checks if the action server is active, and I can tell from your logs that it is not.

Could you please check what is happening to /Move, /RobMove, and /RobPose when you launch the ROS 2 environment? I had a similar issue some time ago after a general ROS 2 Humble and MoveIt!2 update, which I solved by simply re-compiling my ROS 2 workspace:

1. Remove the build, log and install folders in /dev_ws
2. sudo apt update and sudo apt upgrade
3. colcon build to completely re-build the workspace

Do let me know if this solution works, happy to help!

Regards,
Mikel

**Comment by SeanM-IRL** [comment]
Hello Mike 
Thanks for your reply, I checked those actions and they all show as no active action server, I tried the steps but unfortunately it didn't fix it for me, I don't have any further time to look into it,

**Comment by greyflon** [comment]
Worked for me. Thank you! Issue closed.
